import React, { useState } from 'react';
import { 
  Navigation, 
  MapPin, 
  ShieldCheck, 
  AlertOctagon, 
  CornerDownRight, 
  Clock, 
  Compass, 
  Info,
  Layers,
  ArrowRight
} from 'lucide-react';
import { EvacuationResult, SituationResult } from '../types';

interface EvacuationPageProps {
  evacuation: EvacuationResult;
  situation: SituationResult;
}

export const EvacuationPage: React.FC<EvacuationPageProps> = ({
  evacuation,
  situation
}) => {
  const [selectedNode, setSelectedNode] = useState<string | null>('shelter');

  const nodes = [
    {
      id: 'origin',
      title: 'Incident Origin / Inundation Zone',
      subtitle: situation.affected_area,
      status: 'High Hazard Vector',
      badgeColor: 'bg-rose-500/20 text-rose-300 border-rose-500/40',
      x: 15,
      y: 70,
      details: 'Submerged residential low-lying zone. Water level rising. Direct boat extraction required.'
    },
    {
      id: 'avoid-1',
      title: 'Hazard Choke: Submerged Underpass',
      subtitle: 'Rail Bridge Subway',
      status: 'ROAD CLOSED / SUBMERGED',
      badgeColor: 'bg-red-600/30 text-red-200 border-red-500',
      x: 35,
      y: 80,
      details: 'Depth > 4 ft. Submerged electrical transformers. Strictly impassable for all vehicular transport.'
    },
    {
      id: 'corridor-1',
      title: 'Waypoint 1: Kanithi Elevated Ring Road',
      subtitle: 'Elevated High-Clearance Highway',
      status: 'OPEN - RECOMMENDED CORRIDOR',
      badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      x: 45,
      y: 40,
      details: 'High-elevation corridor free from standing water. Assigned for rescue dinghies and army trucks.'
    },
    {
      id: 'corridor-2',
      title: 'Waypoint 2: Sector 3 Flyover Junction',
      subtitle: 'Traffic Police Traffic Control Post Alpha',
      status: 'CONTROLLED TRANSIT',
      badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40',
      x: 70,
      y: 35,
      details: 'Traffic marshals directing evacuees directly into the school relief campus gates.'
    },
    {
      id: 'shelter',
      title: 'Destination: Emergency Relief Center A',
      subtitle: evacuation.recommended_shelter,
      status: 'SAFE HAVEN - ACTIVE TRIAGE',
      badgeColor: 'bg-emerald-500/30 text-emerald-200 border-emerald-400 font-bold',
      x: 88,
      y: 25,
      details: 'Elevated concrete campus. Food, potable water, medical beds, and power generators operational.'
    }
  ];

  return (
    <div className="max-w-7xl mx-auto py-6 space-y-8">
      {/* Header */}
      <div className="space-y-2">
        <div className="flex items-center gap-2 text-rose-500 font-mono text-xs font-bold uppercase tracking-wider">
          <Navigation className="w-4 h-4" />
          Screen 6 — Evacuation Route Planning
        </div>
        <h1 className="text-3xl font-extrabold text-white">
          Simulated Evacuation Corridor & Safe Routing
        </h1>
        <p className="text-sm text-slate-400">
          Generated by the Evacuation Agent based on real-time topography, flood risk vectors, and shelter capacities.
        </p>
      </div>

      {/* Mandatory Disclaimer Label */}
      <div className="p-3.5 rounded-2xl bg-amber-500/10 border border-amber-500/40 text-amber-200 text-xs flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Info className="w-4 h-4 text-amber-400 shrink-0" />
          <span className="font-semibold">
            ⚠️ Demo evacuation route — not live navigation.
          </span>
        </div>
        <span className="font-mono text-[11px] bg-amber-500/20 px-2 py-0.5 rounded border border-amber-500/30">
          SIMULATED GIS VECTOR
        </span>
      </div>

      {/* Primary Routing Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-1.5">
          <span className="text-xs text-slate-400 font-mono">Designated Safe Shelter</span>
          <h3 className="text-base font-bold text-emerald-400">
            {evacuation.recommended_shelter}
          </h3>
          <p className="text-xs text-slate-400">High-ground elevated structural shelter with triage</p>
        </div>

        <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-1.5">
          <span className="text-xs text-slate-400 font-mono">Evacuation Priority</span>
          <div className="flex items-center gap-2">
            <span className="text-base font-extrabold text-rose-400 uppercase font-mono">
              {evacuation.evacuation_priority || 'Immediate'}
            </span>
            <span className="text-xs text-slate-400">
              ({evacuation.estimated_travel_time || '15-25 min transit'})
            </span>
          </div>
          <p className="text-xs text-slate-400">Vulnerable populations (elderly/children) first</p>
        </div>

        <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-1.5">
          <span className="text-xs text-slate-400 font-mono">Corridor Clearance</span>
          <h3 className="text-base font-bold text-cyan-400">
            Kanithi Elevated Bypass
          </h3>
          <p className="text-xs text-slate-400">Monitored by NDRF and traffic coordination teams</p>
        </div>
      </div>

      {/* Simulated Map Visualizer */}
      <div className="rounded-3xl bg-slate-900/90 border border-slate-800 overflow-hidden shadow-2xl">
        <div className="p-4 sm:p-5 border-b border-slate-800 flex items-center justify-between flex-wrap gap-2 bg-slate-950/80">
          <div className="flex items-center gap-2 text-xs font-mono text-slate-300">
            <Compass className="w-4 h-4 text-rose-400" />
            <span className="font-bold text-white">GIS VECTOR MAP SIMULATION</span>
            <span className="text-slate-500">| Scale: 1:15,000 DEMO GRID</span>
          </div>
          <div className="flex items-center gap-3 text-xs font-mono">
            <span className="flex items-center gap-1.5 text-emerald-400">
              <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
              Green: Recommended Path
            </span>
            <span className="flex items-center gap-1.5 text-rose-400">
              <span className="w-2.5 h-2.5 rounded-full bg-rose-500" />
              Red: Danger Zone (Avoid)
            </span>
          </div>
        </div>

        {/* Map Canvas / SVG Topology */}
        <div className="relative w-full h-80 sm:h-96 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 overflow-hidden p-4">
          {/* Grid lines */}
          <div className="absolute inset-0 bg-[linear-gradient(to_right,#1e293b15_1px,transparent_1px),linear-gradient(to_bottom,#1e293b15_1px,transparent_1px)] bg-[size:40px_40px]" />

          {/* SVG Routes & Connections */}
          <svg className="absolute inset-0 w-full h-full pointer-events-none">
            {/* Primary Recommended Safe Route (Green Glow) */}
            <path
              d="M 120 220 Q 280 180 400 130 T 750 90"
              fill="none"
              stroke="#10b981"
              strokeWidth="4"
              strokeDasharray="6 6"
              className="animate-pulse"
            />
            {/* Danger detour line (Red broken) */}
            <path
              d="M 120 220 Q 250 270 320 260"
              fill="none"
              stroke="#ef4444"
              strokeWidth="3"
              strokeDasharray="4 4"
              opacity="0.6"
            />
            {/* Alternative Route (Yellow) */}
            <path
              d="M 120 220 Q 350 70 750 90"
              fill="none"
              stroke="#f59e0b"
              strokeWidth="2"
              strokeDasharray="4 4"
              opacity="0.4"
            />
          </svg>

          {/* Node Markers on the Map */}
          {nodes.map((node) => {
            const isSelected = selectedNode === node.id;
            return (
              <button
                key={node.id}
                onClick={() => setSelectedNode(node.id)}
                style={{ left: `${node.x}%`, top: `${node.y}%` }}
                className={`absolute -translate-x-1/2 -translate-y-1/2 p-2.5 rounded-2xl border transition-all cursor-pointer group ${
                  node.id === 'shelter'
                    ? 'bg-emerald-500/20 border-emerald-400 hover:scale-110 shadow-lg shadow-emerald-950'
                    : node.id === 'origin'
                    ? 'bg-rose-500/20 border-rose-500 hover:scale-110 shadow-lg shadow-rose-950'
                    : node.id === 'avoid-1'
                    ? 'bg-red-600/30 border-red-500 hover:scale-110'
                    : 'bg-slate-800/90 border-slate-700 hover:scale-110'
                } ${isSelected ? 'ring-2 ring-white scale-110' : ''}`}
                title={node.title}
              >
                <div className="flex items-center gap-1.5 text-xs font-bold font-mono text-white">
                  {node.id === 'shelter' ? (
                    <ShieldCheck className="w-4 h-4 text-emerald-400" />
                  ) : node.id === 'avoid-1' ? (
                    <AlertOctagon className="w-4 h-4 text-rose-400" />
                  ) : (
                    <MapPin className="w-4 h-4 text-amber-400" />
                  )}
                  <span className="hidden sm:inline text-[11px] whitespace-nowrap">
                    {node.title.split(':')[0]}
                  </span>
                </div>
              </button>
            );
          })}
        </div>

        {/* Selected Node Inspector Drawer */}
        {selectedNode && (
          <div className="p-4 sm:p-5 bg-slate-950 border-t border-slate-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 text-xs">
            {(() => {
              const current = nodes.find((n) => n.id === selectedNode);
              if (!current) return null;
              return (
                <>
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-white text-sm">{current.title}</span>
                      <span className={`px-2 py-0.5 rounded text-[10px] font-mono border ${current.badgeColor}`}>
                        {current.status}
                      </span>
                    </div>
                    <p className="text-slate-400">{current.details}</p>
                  </div>
                  <span className="font-mono text-[11px] text-slate-500 shrink-0">
                    Coords: {current.x * 10}, {current.y * 10}
                  </span>
                </>
              );
            })()}
          </div>
        )}
      </div>

      {/* Suggested Routes & Avoidances Detail Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Suggested Route Details */}
        <div className="p-6 rounded-3xl bg-slate-900/80 border border-slate-800 space-y-4">
          <div className="flex items-center gap-2 text-emerald-400 font-bold text-base">
            <CornerDownRight className="w-5 h-5" />
            <span>Primary Suggested Route</span>
          </div>
          <div className="p-4 rounded-2xl bg-slate-950/70 border border-slate-800 text-sm text-slate-200 leading-relaxed font-mono">
            {evacuation.suggested_route}
          </div>

          {evacuation.alternative_route && (
            <div className="pt-2">
              <span className="text-xs font-semibold text-amber-400 block mb-1.5 font-mono">
                Alternative Secondary Bypass:
              </span>
              <p className="text-xs text-slate-300 bg-amber-500/5 p-3 rounded-xl border border-amber-500/20 font-mono">
                {evacuation.alternative_route}
              </p>
            </div>
          )}
        </div>

        {/* Areas to Avoid */}
        <div className="p-6 rounded-3xl bg-slate-900/80 border border-slate-800 space-y-4">
          <div className="flex items-center gap-2 text-rose-400 font-bold text-base">
            <AlertOctagon className="w-5 h-5" />
            <span>High-Risk Areas & Roads to Avoid</span>
          </div>

          <div className="space-y-2.5">
            {evacuation.areas_to_avoid.map((area, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl bg-rose-500/10 border border-rose-500/30 text-xs text-rose-200 flex items-start gap-2.5"
              >
                <span className="font-mono font-bold text-rose-400 shrink-0">⚠ {idx + 1}.</span>
                <span className="leading-snug">{area}</span>
              </div>
            ))}
          </div>

          {evacuation.hazard_zone_notes && (
            <p className="text-xs text-slate-400 italic pt-2">
              Ground Note: {evacuation.hazard_zone_notes}
            </p>
          )}
        </div>
      </div>
    </div>
  );
};
